web:
  enabled: true
  port: 8080
  url: "http://schemati.openredstone.org:8080/"
  oauth:
    clientId: "***"
    clientSecret: "***"
    scopes:
      - "identify"

network_database:
  port: 3306
  host: "localhost"
  database: "***"
  username: "***"
  password: "***"

# Some folder the server can read/write to
schematicsDirectory: "./schems"
